spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cm
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: shidi
    type: org.apache.commons.dbcp.BasicDataSource
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.springbootmybatis.mapper
logging:
  level:
    com.springbootmybatis: DEBUG

